[site]
title = "谭梦莎"
description = "哥伦比亚大学硕士生个人主页。"
last_updated = "2026年06月06日"

[author]
name = "谭梦莎"
title = "硕士生"
institution = "哥伦比亚大学"

[social]
location = "纽约，美国"
location_details = [
  "622 W. 168th Street, PH20",
  "New York, NY 10032, United States"
]

[[navigation]]
title = "关于我"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "论文"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "教育经历"
type = "page"
target = "teaching"
href = "/teaching"

# [[navigation]]
# title = "奖项"
# type = "page"
# target = "awards"
# href = "/awards"

# [[navigation]]
# title = "服务"
# type = "page"
# target = "services"
# href = "/services"

[[navigation]]
title = "简历"
type = "page"
target = "cv"
href = "/cv"
